# Generated by Django 2.0.2 on 2018-04-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20180423_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('plan', models.TextField()),
                ('joined_by', models.ManyToManyField(related_name='joined_trip', to='exam_app.User')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned', to='exam_app.User')),
            ],
        ),
    ]
